module.exports = {
  parser: '@babel/eslint-parser',
  plugins: ['sonarjs', 'no-secrets', 'node', 'prettier'],
  extends: ['airbnb', 'plugin:sonarjs/recommended', 'plugin:prettier/recommended'],
  globals: {'window': 'writable'},
  settings: {
    tagNamePreference: {
      augments: 'extends',
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.mjs', '.jsx', '.ts', '.tsx'],
      },
      exports: {
        require: false,
        browser: false,
        conditions: [],
        unsafe: false,
      },
    },
  },
  rules: {
    'no-nested-ternary': ['off'],
    radix: ['off'],
    'prettier/prettier': [
      'warn',
      {
        trailingComma: 'all',
        printWidth: 120,
        tabWidth: 2,
        semi: true,
        singleQuote: true,
        bracketSpacing: true,
        arrowParens: 'always',
        endOfLine: 'lf',
      },
    ],
    curly: ['error', 'multi-line'],
    'sonarjs/no-duplicate-string': ['warn'],
    'sonarjs/cognitive-complexity': ['warn'],
    'no-unused-vars': ['warn', { varsIgnorePattern: '^_+$', argsIgnorePattern: '^_+$' }],
    'no-empty': ['warn', { allowEmptyCatch: true }],
    'no-secrets/no-secrets': ['error', { ignoreContent: ['^https://', '^http://'] }],
    quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: true }],
    'max-len': ['warn', 180],
    'jsx-a11y/anchor-is-valid': ['warn'],
    'react/static-property-placement': ['error', 'static public field'],
    'react/jsx-filename-extension': ['error', { extensions: ['.js', '.ts'] }],
    'react/forbid-prop-types': ['off'],
    'react/prefer-stateless-function': ['off'],
    'react/jsx-props-no-spreading': ['off'],
    'react/jsx-one-expression-per-line': ['off'],
    'react/state-in-constructor': ['off'],
    'react/prop-types': 'off',
    'react/react-in-jsx-scope': 'off',
    'consistent-return': ['off'],
    'class-methods-use-this': ['off'],
    'comma-dangle': [
      'error',
      {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'always-multiline',
      },
    ],
    'no-restricted-syntax': ['error', 'LabeledStatement', 'WithStatement'],
    'node/no-deprecated-api': ['error'],
    'node/no-extraneous-import': ['error'],
    'node/no-extraneous-require': ['error'],
    'node/no-exports-assign': ['error'],
    'node/no-unpublished-bin': ['error'],
    'node/no-unpublished-import': ['error'],
    'node/no-unpublished-require': ['error'],
    'node/process-exit-as-throw': ['error'],
    'node/shebang': ['error'],
    'node/prefer-promises/fs': ['error'],
    'node/prefer-promises/dns': ['error'],
    'node/no-process-env': ['error'],
    'node/exports-style': ['error', 'module.exports'],
    'import/prefer-default-export': ['off'],
    'import/extensions': [
      'error',
      'ignorePackages',
      {
        js: 'never',
        mjs: 'never',
        jsx: 'never',
        ts: 'never',
        tsx: 'never',
      },
    ],
  },
};
